### ISSUE TITLE
why is this using react in register

### ISSUE THREAD

**Issue by naveenkash** [vuetifyjs/vue-cli-plugins#160]
i tried to serve this with react code but it throws the error so i removed the react file and it works fine now so why using react in vue?

**Comment by jacekkarczmarczyk** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
