### ISSUE TITLE
"vue add vuetify" is overriding existing files

### ISSUE THREAD

**Issue by IgorIlgiyaev** [vuetifyjs/vue-cli-plugins#249]
Hey.

I have installed yesterday Vuetify on an existing project to make the app prettier but have encounter some
 issues after (Default)install.
1: After install files have been overwritten and deleting the existing files (image attached).
1a: files like: app.vue|package.json and etc.
This is only one example but had a lot of changes in the package.json on the default install (not Advanced).
<img width="1281" alt="Screen Shot 2021-03-07 at 11 12 17" src="https://user-images.githubusercontent.com/20319110/110234997-4a831c00-7f36-11eb-8ed7-34a78fa56f54.png">

**Comment by ElijahKotyluk** [comment]
Would you be able to provide a reproduction link to the repository?

**Comment by IgorIlgiyaev** [comment]
Will send you here in a few hours so you can check it in the commits area.

**Comment by ElijahKotyluk** [comment]
Perfect, I'll give it a look and figure out what's going on. Thank you.

**Comment by ElijahKotyluk** [comment]
I got a chance to go through the repro you provided, so as far as the App.vue goes and main.js, those files do get replaced due to the current CLI API not provided a way to easily extend the root vue instance. I can write up a more elegant way to just inject the code when/where necessary to solve that.

As far as the config file, it looks like in this commit : https://github.com/IgorIlgiyaev/taskmanager/commit/2e1940d2baf177c9784b2e1181cf0440d0e470c2 it does get updated and the transpile dependencies key is provided when you add Vuetify.
But in this commit gets removed with the code that was in there prior: https://github.com/IgorIlgiyaev/taskmanager/commit/5f78aed000e84c4184fb96d94ff415ab43411a4f

**Comment by IgorIlgiyaev** [comment]
Exactly :-)
Hope that will help you to solve it as I am pretty new to Vue and Vuetify and learning as I am a WP site builder :-)

**Comment by ElijahKotyluk** [comment]
To get around having your files replaced you can select the `configure` option and enter no at the following prompt:
`Use a pre-made template? (will replace App.vue and HelloWorld.vue)`
